//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gmcGPU.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GMCGPU_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_CONTROL                     130
#define IDD_PNL_SETUP                   130
#define IDD_BLOCK                       132
#define IDD_PNL_CTRL                    133
#define IDD_PNL_RESULTS                 135
#define IDD_DLG_SAVE_DICOM              141
#define IDB_BITMAP1                     143
#define IDB_BITMAP2                     144
#define IDB_BITMAP3                     145
#define IDB_BITMAP4                     148
#define IDB_BITMAP5                     149
#define IDB_BITMAP6                     150
#define IDB_BITMAP7                     151
#define IDD_DLG_PLAN_GET_PACS           152
#define IDD_PNL_CONFIG                  154
#define IDD_DLG_SAVE_QA                 156
#define IDD_DLG_PARAMS_GAMMA            158
#define IDD_DLG_GAMMA_THESHES           158
#define IDD_DIALOG1                     160
#define IDD_PNL_PACS_MONITOR            160
#define IDC_BTN_SAVE                    1001
#define IDC_BTN_VIEW                    1002
#define IDC_COMBO_BLK_MAT               1003
#define IDC_BTN_SAVE2                   1003
#define IDC_BTN_MSH_IN                  1003
#define IDC_EDIT3                       1004
#define IDC_BTN_SAVE3                   1004
#define IDC_BTN_SAVE4                   1005
#define IDC_BTN_SAVE_RAW                1005
#define IDC_BTN_PLUS                    1006
#define IDC_BTN_ZOOM_UP                 1006
#define IDC_EDIT4                       1007
#define IDC_EDIT5                       1008
#define IDC_BTN_MINUS                   1009
#define IDC_BTN_ZOOM_DOWN               1009
#define IDC_EDIT8                       1012
#define IDC_EDIT9                       1013
#define IDC_EDIT10                      1014
#define IDC_EDIT11                      1015
#define IDC_EDIT12                      1016
#define IDC_SLIDER_DOSE                 1016
#define IDC_EDIT13                      1017
#define IDC_EDIT6                       1017
#define IDC_EDIT14                      1018
#define IDC_EDIT7                       1018
#define IDC_COMBO_BLK_NUM               1019
#define IDC_EDIT15                      1019
#define IDC_COMBO_BLK_TYPE              1020
#define IDC_BTN_JSON                    1021
#define IDC_BTN_JSON2                   1022
#define IDC_BTN_PLAYER                  1022
#define IDC_BTN_DICOM                   1023
#define IDC_EDIT1                       1024
#define IDC_CHK_QA                      1025
#define IDC_EDIT2                       1025
#define IDC_EDIT_DOSE                   1026
#define IDC_EDT_MAX                     1026
#define IDC_CHK_DIJ                     1026
#define IDC_EDIT16                      1026
#define IDC_BTN_RUN_PLAN                1027
#define IDC_BTN_TILE5                   1027
#define IDC_STC_DOSE_MAX_SEC            1027
#define IDC_COMBO_CAV_MAT               1028
#define IDC_STATIC_EXT_DOSE_MAX         1028
#define IDC_BTN_RUNPLAN2                1028
#define IDC_CHK_PACS                    1028
#define IDC_COMBO_CAV_TYPE              1029
#define IDC_EDIT_DOSE_                  1029
#define IDC_EDT_MIN                     1029
#define IDC_BTN_RUNPLAN3                1029
#define IDC_BTN_RUN_QA                  1029
#define IDC_CMB_PROTON_SCALE            1030
#define IDC_STATIC_EXT_DOSE_MAX2        1031
#define IDC_STC_DOSE_MAX_PRIM           1031
#define IDC_CHK_AUX                     1031
#define IDC_RADIO_DOSE                  1032
#define IDC_RADIO1                      1032
#define IDC_RADIO2                      1033
#define IDC_RADIO3                      1034
#define IDC_RADIO4                      1035
#define IDC_RADIO5                      1036
#define IDC_RADIO6                      1037
#define IDC_RDO_ALL                     1037
#define IDC_RADIO7                      1038
#define IDC_CHK_ALL                     1038
#define IDC_RADIO8                      1039
#define IDC_RADIO9                      1040
#define IDC_RADIO10                     1041
#define IDC_CMB_NUM_CYCLES              1042
#define IDC_RADIO11                     1042
#define IDC_RADIO12                     1043
#define IDC_CHECK1                      1044
#define IDC_BTN_VIEW2                   1044
#define IDC_CHECK2                      1045
#define IDC_BTN_COMPUTED                1045
#define IDC_CHECK3                      1046
#define IDC_BTN_DOSE_DICOM              1046
#define IDC_CHECK4                      1047
#define IDC_BTN_APERTURES               1047
#define IDC_BTN_DOSE_RAW                1047
#define IDC_CHECK5                      1048
#define IDC_BTN_RESAMPLE                1048
#define IDC_CHECK6                      1049
#define IDC_BTN_HISTOGRAMS              1049
#define IDC_CHECK7                      1050
#define IDC_BTN_HISTOGRAMS2             1050
#define IDC_BTN_DOSE_DICOM2             1050
#define IDC_BTN_DICOM_SAVE              1050
#define IDC_CHECK8                      1051
#define IDC_BTN_PROFILE                 1051
#define IDC_BTN_SPOT                    1052
#define IDC_BTN_RESULTS                 1052
#define IDC_BTN_RESULT_TYPE_PRIM        1052
#define IDC_BTN_DOSE_DIFF               1053
#define IDC_BTN_SPOT2                   1054
#define IDC_BTN_IMG_DATA                1054
#define IDC_BTN_IMAGE_DATA              1054
#define IDC_BTN_DOSE_DIFF2              1054
#define IDC_BTN_DOSE_SUM_BEAMS          1054
#define IDC_BTN_SPOT_DOSE               1055
#define IDC_BTN_PROFILE2                1055
#define IDC_BTN_ANGLE                   1055
#define IDC_BTN_SAVE_BIO                1055
#define IDC_BTN_RESULTS2                1055
#define IDC_BTN_RESULTS_TYPE_SEC        1055
#define IDC_BTN_DOSE_SUM_EXTRNL         1055
#define IDC_BTN_DOSE_SUM_EXTRNL2        1056
#define IDC_STC_NUM_PROTONS             1057
#define IDC_BUTTON1                     1058
#define IDC_BTN_ENERGY                  1058
#define IDC_BTN_QUERY                   1058
#define IDC_TAB1                        1059
#define IDC_STC_NUM_PROTONS2            1059
#define IDC_STC_NUM_SPOTS               1059
#define IDC_STC_ID                      1059
#define IDC_BTN_QUERY2                  1059
#define IDC_BTN_RETRIEVE                1059
#define IDC_BTN_GAMMA                   1059
#define IDC_EDT_NUM                     1060
#define IDC_EDT_NUM_PROTONS_SPOT        1061
#define IDC_EDT_DESCRIPTION             1062
#define IDC_STC_PLAN_NAME               1062
#define IDC_EDT_JSON_PLAN               1063
#define IDC_STATIC2                     1064
#define IDC_STC_COLOR_SCALE             1065
#define IDC_STC_NUM_SPOTS3              1065
#define IDC_STC_SERIES_DESCR            1065
#define IDC_COMBO1                      1066
#define IDC_STC_PLAN                    1066
#define IDC_BTN_TILE1                   1067
#define IDC_COMBO2                      1067
#define IDC_STC_NUM_PROTONS_PLAN        1067
#define IDC_BTN_TILE2                   1068
#define IDC_COMBO5                      1068
#define IDC_BTN_TILE3                   1069
#define IDC_COMBO3                      1069
#define IDC_BTN_TILE4                   1070
#define IDC_COMBO4                      1070
#define IDC_STC_RBEAB                   1071
#define IDC_COMBO6                      1071
#define IDC_STC_DOSE_MIN                1072
#define IDC_STC_DOSE_MAX                1073
#define IDC_BTN_PACS                    1074
#define IDC_LIST2                       1075
#define IDC_LIST1                       1076
#define IDC_CMB_PRIM                    1077
#define IDC_CMB_RESULTS_PRIM            1077
#define IDC_STC_GIF                     1078
#define IDC_CMB_RESULTS_PRIM2           1078
#define IDC_CMB_RESULTS_SEC             1078
#define IDC_STC_STATUS                  1079
#define IDC_STC_SELECT                  1080
#define IDC_STC_                        1081
#define IDC_STC_COMPUTING               1081
#define IDC_BTN_STRUCTS                 1082
#define IDC_CHK_AUTO                    1084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
